### ISSUE TITLE
AddLoginAsync bug

### ISSUE THREAD

**Issue by ruskom** [kriasoft/AspNet-Server-Template#5]
Hi,

There is a typo in AspNet-Server-Template/src/App.Server/Data/UserStore.cs in method AddLoginAsync at line 148.
Instead of 
userLogin.LoginProvider = login.ProviderKey;
would be
userLogin.LoginProvider = login.LoginProvider;

It makes using external logins unusable.

Cheers,
Marton

**Comment by koistya** [comment]
Thanks for the report!
